#!/bin/bash
#PBS -N qiime_20151002
#PBS -S /bin/bash
#PBS -q UCTlong
#PBS -l nodes=1:series600:ppn=4
#PBS -V
#PBS -M gerrit.botha@uct.ac.za
#PBS -d /scratch/researchdata/cbio/medmicbio/project08/process/team/gerrit/runs/20151002/16S/qiime/logs

source /home/gerrit/activate_qiime.sh
inDir=/scratch/researchdata/cbio/medmicbio/project08/process/team/gerrit/runs/20151002/16S/uparse/uparse_downstream
outDir=/scratch/researchdata/cbio/medmicbio/project08/process/team/gerrit/runs/20151002/16S/qiime

biom convert -i $inDir/otus_table.tab.txt -o $outDir/otus_table.biom --table-type="otu table"

assign_taxonomy.py -i $inDir/otus_repsetOUT.fa -o $outDir/tax -r /scratch/DB/bio/qiime/greengenes/gg_13_8_otus/rep_set/97_otus.fasta -t /scratch/DB/bio/qiime/greengenes/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt -m rdp -c 0.5

biom add-metadata -i $outDir/otus_table.biom -o $outDir/otus_table.tax.biom --observation-metadata-fp $outDir/tax/otus_repsetOUT_tax_assignments.txt --observation-header OTUID,taxonomy,confidence --sc-separated taxonomy --float-fields confidence 

align_seqs.py -i $inDir/otus_repsetOUT.fa -o $outDir/rep_set_align -t /scratch/DB/bio/qiime/greengenes/gg_13_8_otus/rep_set_aligned/97_otus.fasta

filter_alignment.py -i $outDir/rep_set_align/otus_repsetOUT_aligned.fasta -o $outDir/filtered_alignment

make_phylogeny.py -i $outDir/filtered_alignment/otus_repsetOUT_aligned_pfiltered.fasta -o $outDir/filtered_alignment/otus_repsetOUT_aligned_pfiltered.tre

biom summarize-table -i $outDir/otus_table.tax.biom -o $outDir/otus_table.tax.biom.summary
